---
# Vim plugin installation for ansible-role-vim.
#
# Installs one plugin.

- name: Determine plugin name.
  ansible.builtin.set_fact:
    vim_plugin_name: "{{ (vim_plugin_install.repo | basename | splitext)[0] }}"

- name: Determine plugin install directory.
  ansible.builtin.set_fact:
    vim_plugin_dest: "{{ vim_plugin_parent_directory }}/{{ vim_pack_subdirectory }}/{{ vim_plugin_install.type|default('start') }}/{{ vim_plugin_name }}"

- name: Create a path to search for '{{ vim_plugin_name }}' helptags.
  ansible.builtin.set_fact:
    vim_plugin_doc: "{{ vim_plugin_dest }}/doc"

- name: Find out if the plugin already exists.
  ansible.builtin.stat:
    path: "{{ vim_plugin_dest }}"
  register: vim_plugin_dest_dir

- name: Find out if the '{{ vim_plugin_name }}' plugin contains a doc/ directory.
  ansible.builtin.stat:
    path: "{{ vim_plugin_doc }}"
  register: vim_plugin_doc_dir
  changed_when: false

- name: Clone '{{ vim_plugin_name }}' plugin into place.
  ansible.builtin.git:
    clone: true
    dest: "{{ vim_plugin_dest }}"
    # Force only when there's a previously existing doc/ directory in the plugin
    # since Ansible will interpret this as local changes to the repo.
    force: "{{ vim_plugin_doc_dir.stat.exists }}"
    repo: "{{ vim_plugin_install.repo }}"
    update: true
    version: "{{ vim_plugin_install.version | default('HEAD') }}"
  become: true
  become_user: "{{ vim_owner }}"
  register: vim_plugin_clone
  # Mark this task changed only when a) it actually changed, AND b) the plugin
  # directory already existed prior to this task running, AND c) the doc/
  # directory didn't actually exist prior to this task running.
  #
  # This is crude, but it accounts for the case where we force clone.
  changed_when:
    - vim_plugin_clone.changed
    - vim_plugin_dest_dir.stat.exists
    - not vim_plugin_doc_dir.stat.exists
